services:
  - type: web
    name: engsci-survey-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDirectory: backend
    envVars:
      - key: MONGO_USER
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: PORT
        value: 10000  # Port for Render to expose
