services:
  - type: web
    name: engsci-survey-backend
    env: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start  # Use npm start for consistency
    envVars:
      - key: MONGO_USER
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: PORT
        value: 10000  # Port for the backend service
